disp("Matrix 1");
disp(rand(3,4));
disp(" ");
disp("Matrix 2");
disp(rand(3,4));
disp(" ");
disp("Matrix 3");
disp(rand(3,4));
disp(" ");
disp("Matrix 4");
disp(rand(3,4));
disp(" ");
disp("Matrix 5");
disp(rand(3,4));
